[config]
# XBOS namespace and filename
namespace = "my-site-name"
# ontology URI to use for model
ontology = "http://xbos.io/ontologies/my-site-name"
# Turtle file containing extra classes we want to use
extra_classes = "extra_classes.ttl"

[xbos]
    [xbos.config]
    # base URI of XBOS archiver
    archiver = "ucberkeley"

    # Adds Green Button meter
    [xbos.GreenButton]
    driver  = "mason.driver.greenbutton"
    # account number
    subid = 111111
    # meter identifier
    uuid = 1111111111

    ## Adds NWS data
    [xbos.NationalWeatherService]
    driver = "mason.driver.nationalweatherservice"
    stations = [
        "AT565",
        "KTLC1",
    ]

    [xbos.Revit]
    driver = "mason.driver.revit"
    revit_schedule = "my-site-name.txt"
